const types = {
  // Joke
  JOKE_DATA_FETCH_START: 'JOKE_DATA_FETCH_START',
  JOKE_DATA_FETCH_SUCCESS: 'JOKE_DATA_FETCH_SUCCESS',
  JOKE_DATA_FETCH_ERROR: 'JOKE_DATA_FETCH_ERROR',
  JOKE_ADD_IS_FAVORITE_FLAG: 'JOKE_ADD_IS_FAVORITE_FLAG',

  // favorite
  FAVORITE_ADD: 'FAVORITE_ADD',
  FAVORITE_DEL: 'FAVORITE_DEL',
  // FAVORITE_ERROR:"FAVORITE_ERROR"
};

export default types;
