const types = {
  // Joke
  JOKE_DATA_FETCH_START: 'JOKE_DATA_FETCH_START',
  JOKE_DATA_FETCH_SUCCESS: 'JOKE_DATA_FETCH_SUCCESS',
  JOKE_DATA_FETCH_ERROR: 'JOKE_DATA_FETCH_ERROR',

  //      // JOKE_DATA_FAVORITES_FETCH_START:
  //   JOKE_DATA_FAVORITES_FETCH_SUCCES: 'global/FETCH_FINISH',
  // // JOKE_DATA_FAVORITES_FETCH_ERROR:
  //   GLOBAL_FETCH_ERROR: 'global/FETCH_ERROR',
};

export default types;
